apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discord-api
  template:
    metadata:
      labels:
        app: discord-api
    spec:
      containers:
      - name: discord-api
        image: sabrysuperman/discord-api:latest
        ports:
        - containerPort: 80
